### ISSUE TITLE
Stray html tag in doctype

### ISSUE THREAD

**Issue by jbrgfx** [FPtje/miso-isomorphic-example#10]
See: https://github.com/dmjio/miso/issues/429
and: https://github.com/dmjio/miso/commit/93783297bd79685b7a471bc565bcdc801c270b02

**Describe the bug**
https://github.com/FPtje/miso-isomorphic-example/blob/master/server/Main.hs 
block beginning on line 77 produces an HTML validation error.
```
instance L.ToHtml a => L.ToHtml (HtmlPage a) where
    toHtmlRaw = L.toHtml
    toHtml (HtmlPage x) =
        L.doctypehtml_ $ do
          L.head_ $ do
```
Causes an Error: 
Start tag in generated HTML5 missing lang attribute, then it is added but wrapped in a duplicate html tag.

Extra html tag opened and closed after ending head and before body
```
<!DOCTYPE HTML><html><html lang="en"><head><title>  </head></html><body>
```

Your "wrapper implementation" fails to implement lucid output as prescribed in the lucid documentation.

**To Reproduce**
1. Run project
2. View source
3. Inspect DOCTYPE
4. submit generated HTML to https://validator.w3.org/ 

**Expected behavior**
Output should be:
```
<!DOCTYPE HTML><html lang="en"><head><title> </title><meta charset="utf-8"><script defer async src="/static/all.js"></script></head><body>
```

refactored code:
```
    toHtml (HtmlPage x) = do
      L.doctype_
      L.html_ [ L.lang_ "en" ] $ do
```

**Additional context**
Using lucid directly produces the proper output.
```   
page :: Html () 
   page =
      html_ [lang_ "en"]
         (do head_  
             body_
```
 produces:
```
   <html lang="en"><head>  </head><body>
```

**Comment by jbrgfx** [comment]
Really useful demo and helpful description of the implementation.

**Comment by FPtje** [comment]
Shamelessly copying fix from @dmjio
