### ISSUE TITLE
Having trouble making the client available to the server

### ISSUE THREAD

**Issue by peterstorm** [FPtje/miso-isomorphic-example#18]
Hello!

As a learning experience, I'm trying to see if I can finangle your awesome example out to be a simple blog.

But I have trouble with the last part where you have to make the client available to the server, by doing the following:

```
cd server
mkdir static
ln -sf ../$(find ../client -name all.js) static/
```

I just get:

```
ln: static/..: cannot overwrite directory
```

Can you help with this? Thank you in advance!

**Comment by FPtje** [comment]
Hmm, that `ln` error is thrown when telling `ln` to make a link at a path where there's already a directory instead. I've managed to reproduce the issue, but that error points in the completely wrong direction as to what the problem actually is.

I get the same error when running that command while the client hasn't been built yet. Make sure you run this part of the guide:

```bash
cd client
nix-shell
cabal build
...
exit
```

In the `client/` directory, you should have a `dist` folder after running the above commands. Deep down in there (`dist/build/client/client.jsexe/` to be precise) is the `all.js` file. That needs to exist for the `ln` command to succeed.

This is what the `ln` command (with the `find` subcommand) actually does in practice:
```bash
ln ../client/dist/build/client/client.jsexe/all.js static/all.js
```
If the command still fails, you can try running that instead. That one1 at least gave me a more descriptive error when it went wrong.

I've made a change to the `README.md` to better explain that the client needs to be built before it can be copied over to the server. See 1544c4b.

**Comment by peterstorm** [comment]
When I try to build the client though, which I probably should have mentioned it says it can’t because it is set to ‘buildable = false’.

**Comment by FPtje** [comment]
The buildable flag is set in the cabal file only when ghc is used instead of ghcjs. Are you using nix-shell? Cabal should automatically pick up that ghcjs is to be invoked when compiling the client. The `cabal.config` file states so.

**Comment by FPtje** [comment]
Maybe there's some debug flag to cabal build.  Try running with `--compiler ghcjs`.

I should really look into the newer cabal

**Comment by peterstorm** [comment]
The original guide worked when I did `cabal build --ghcjs` in the client folder, thank you :)

**Comment by andremarianiello** [comment]
I just ran into this. The README doesn't mention anything about the --ghcjs flag. cabal.config has `compiler: ghcjs` but that doesn't seem to have done anything. Something should be updated to make coming to this issue unnecessary.
