### ISSUE TITLE
Add test for the client and the server and a shell.nix to run them

### ISSUE THREAD

**Issue by voidus** [FPtje/miso-isomorphic-example#19]
For the server, a shell that contains ghcid would be nice. AFAIK ghcjs8 currently doesn't support --interactive, so just a command that runs the client tests would be great.

**Comment by FPtje** [comment]
I've decided to decline this for the same reason as stated in [here](https://github.com/FPtje/miso-isomorphic-example/issues/20#issuecomment-546629996).

Tests aren't necessary for an example, so I'd like to keep the example focused on being minimal.

Thanks for the suggestion, though.
