### ISSUE TITLE
install problems

### ISSUE THREAD

**Issue by odr** [FPtje/miso-isomorphic-example#2]
I had two problems with installation of client. (I tried stack than nix also).
At the end I've got success with following
- in .cabal file I delete "ghc-option: -dedupe" for client executable because this flag was added only for ghcjs-0.2.1
- in client/Main.hs comment out TypeApplications and change "Proxy @X" to "Proxy :: Proxy X" everywhere

**Comment by FPtje** [comment]
Hmm, I'm not sure I should support older versions of ghcjs. Is there any specific reason you chose for this version of ghcjs?

**Comment by odr** [comment]
Version 0.2.0 is written in stack.yaml. I didn't change it.
Probably you can change it to 0.2.1 and ghc8.0.1. But as I understand ghcjs-ghci works only with ghc7.10.3-ghcjs0.2.0.

**Comment by FPtje** [comment]
The `stack.yaml` file was kind of misleading. It was untested and it shouldn't even work by the looks of it. I removed it in favour of building it with nix. To facilitate building with nix, nixpkgs are now pinned in `default.nix`.

**Comment by tkvogt** [comment]
It currently doesn't work. I get:

> error: store path mismatch in file downloaded from 'https://github.com/NixOS/nixpkgs-channels/archive/c1d9aff56e0ae52ee4705440fe09291a51e91977.tar.gz'

What I suspect: In the default.nix of the base directory, there is

```
miso-src = pkgs.fetchFromGitHub {
    rev = "adea51505f30853caae76f38faa5e9f192ae8827";
    sha256 = "0x8dik2cx5j11svb091pzy2ycvhbb88534fng2v9bic5yx1a8c72";
    owner = "haskell-miso";
    repo = "miso";
  };
```

But there is no miso repo in
https://github.com/haskell-miso

**Comment by FPtje** [comment]
Fixed, it was the pinned nixpkgs, somehow the sha256 had changed.

I've also updated Miso.
