### ISSUE TITLE
Nix and MacOS Catalina - cannot build server or client with cabal?

### ISSUE THREAD

**Issue by peterstorm** [FPtje/miso-isomorphic-example#23]
Hello!

So I just reinstalled my Mac with MacOS Catalina, and did the work around to install Nix on it, and it seems to be working fine.

I then wanted to try to see if I could manage to not install anything globally and just get by with using Nix environments. So I don't have GHC, Cabal or GHCJS installed anywhere globally, only depending on the nix files.

But when I try to build both the server and the client, it doesn't work, here's what I do:
1. Go to the server directory and nix-shell with this `nix-shell -p cabal-install ghc`. I'm not sure why I need ghc there, because I thought the nix-pkgs.nix file specified that I wanted ghc available, but that doesn't work.
2. Then when I try to build, it says this:
```
[nix-shell:~/dev/haskell/miso-isomorphic-example/server]$ cabal build
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: server-0.1.0.0 (user goal)
[__1] unknown package: common (dependency of server)
[__1] fail (backjumping, conflict set: common, server)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: server, common
```
I've also tried running `cabal --enable-nix build` to see if it was because it was not configured to work with nix, but that doesn't work either.
3. When I try to go build the client, again without GHCJS installed globally, I get this:
```
[nix-shell:~/dev/haskell/miso-isomorphic-example/client]$ cabal build
cabal: Cannot build the package client-0.1.0.0 because none of the components
are available to build: the executable 'client' is marked as 'buildable:
False'


[nix-shell:~/dev/haskell/miso-isomorphic-example/client]$ 
```
And if I try to use the config file in the directory, it say this:
```
[nix-shell:~/dev/haskell/miso-isomorphic-example/client]$ cabal --enable-nix --config-file=cabal.config build
Warning: cabal.config: Unrecognized field packages on line 2
cabal: The program 'ghcjs' version >=0.1 is required but it could not be
found.
```

How do I proceed, thank you in advance.

**Comment by FPtje** [comment]
I cannot test it at the moment, but you need to run the nix shell on the `default.nix` files in the `server/` and `client/` directories, instead of using the `-p` option

**Comment by peterstorm** [comment]
I figured it out, apparently it seems that if I run `nix-shell` with the `-p`flag, it overwrites whatever was loaded in `nix-pgks` so it didn't have access to `ghc` or `ghcjs` when ran it. (I'm a nix noob, so I didn't know that :D )
So I updated the `default.nix`files for, example of the server file her:
```
{ pkgs ? import ../nixpkgs.nix }:

let
  haskellPackages = pkgs.haskell.packages.ghc864;
  server = pkgs.haskell.packages.ghc.callCabal2nix "server" ./. {
    common = pkgs.haskell.packages.ghc.callCabal2nix "common" ../common {};
  };

in
  if pkgs.lib.inNixShell then server.env.overrideAttrs (old: {
      buildInputs = old.buildInputs ++ [ haskellPackages.cabal-install haskellPackages.ghcid ];
  }) else server
```
