### ISSUE TITLE
Extend the example to include how to handle multiple URLs

### ISSUE THREAD

**Issue by tysonzero** [FPtje/miso-isomorphic-example#3]
Once you move from one to multiple URLs you now need to make sure that browsing to each URL gives you the correct local state (both from the server and from the generated javascript), and you also need to make sure that links you click on locally work properly and without a full page reload. So it would be nice to see what the correct way to do the above is; perhaps two urls, a root one and `/flipped` where the buttons are flipped.

**Comment by FPtje** [comment]
A multi-page app has quite a few intricacies, especially with how it's integrated with servant. The example now has the pages you described.

**Comment by tysonzero** [comment]
Thank you so much! My one remaining comment would be that it seems as though it would be nice to have the dispatching between the two views be entirely done in `Common` (i.e. moving `viewModel` and `viewTree` into `Common`, perhaps with `viewTree` adjusted so that you don't have to manually make it match `Common.ClientRoutes`). As it seems like the current setup could "desync" (`Common.homeView $ Common.initialModel Common.flippedLink`).

**Comment by FPtje** [comment]
`viewModel` and `viewTree` are solely used by the client, much like `serverHandlers` and its respective individual servers are used only serverside. As such I disagree that it belongs in `Common`, since that would imply that the functions are common among server and client.

I do agree with manually matching `viewTree` with `Common.ClientRoutes`. The server has a type family solution for this:
```haskell
-- Converts the ClientRoutes (which are a servant tree of routes leading to
-- some `View action`) to lead to `Get '[Html] (HtmlPage (View Common.Action))`
type ServerRoutes
   = ToServerRoutes Common.ClientRoutes HtmlPage Common.Action
```

I can imagine a similar solution for the client side:

```haskell
type ClientRoutes
   = ToClientRoutes Common.ClientRoutes Common.Model Common.Action
``` 
Note that `Common.ClientRoutes` here should be renamed, because here it would have the same name as the `ClientRoutes` I'm defining.

Looking at it like this, `Common.ClientRoutes` sounds like a misnomer, since the server uses the routes to render the `View`s itself before sending it to the client. They're as much server routes as they are client routes. Perhaps it's better to call them `Common.ViewRoutes` or something. That would leave out the implication that they're exclusive to the client.

**Comment by tysonzero** [comment]
It is true that `viewModel` and `viewTree` are only used client side, but I personally feel as though they should be used by the server, so as to prevent the issue I described of being able to desync the choice of server view and the choice of model state.

So I would have the server always render the same view (`viewModel`), regardless of the URL passed in, it would solely be changing the choice of initial model state. That is how the client currently works.

The rest of what you said I agree with.

**Comment by FPtje** [comment]
You very much have a valid point.

**Comment by tysonzero** [comment]
One thing that would be nice, if it's at all possible, is for the server to actually not have it's own set of handlers for every URL, and for it to instead just pass through valid URIs directly into the model, then the views specified in common (`viewModel`) can handle all the routing with no duplication.

Something like:

    serverHandlers :: Server ServerRoutes
    serverHandlers = pure . HtmlPage . viewModel $ initialModel <<URI>>

But I'm not entirely sure how to build something of type `Server ServerRoutes` that is able to just inspect that `URI`.

**Comment by FPtje** [comment]
It must have the same shape as the route tree, that means it has to have the same tree structure of `:<|>` things.

**Comment by tysonzero** [comment]
Is there no way around that? I just do find it a little irksome that we currently have to essentially write out the entire URL structure twice, and it seems like it's possible for them to desync without the type system catching it. For example in this project replacing `serverHandlers = homeServer :<|> flippedServer` with `serverHandlers = flippedServer :<|> homeServer` would not be a type error but it would lead to incorrect behavior.

**Comment by FPtje** [comment]
I must construct something of type `Home :<|> Flipped`. I'm currently doing that by creating the `:<|>` tree and repeating myself, or possibly a type class that does it for me. The latter is way too complicated for an example, though.

**Comment by FPtje** [comment]
The stuff with the type families and servant is definitely complicated, though. Check out the commit and let me know what you think

**Comment by tysonzero** [comment]
Looks good, thank you!

I think the next step will be for me to post a feature request to miso for a function that converts a servant API to handlers of that API via a function passed in of type `URI -> <Endpoint type>`. That way we can simplify `serverHandlers/homeServer/fippedServer` to just `serverHandlers = serveFromURIFunction (Proxy @ServerRoutes) (pure . HtmlPage . Common.viewModel . Common.initialModel)`. This would also mean that you don't have to change it even as you add new urls, which would be very nice.
