### ISSUE TITLE
Consider adding this example to `miso/examples`

### ISSUE THREAD

**Issue by tysonzero** [FPtje/miso-isomorphic-example#8]
It seems like it would make sense to add it in there, for more accessibility and visibility, and so that you can easily test any changes to `miso` itself by seeing how it affects this example.

I'm not suggesting getting rid of this separate repo, as it is nice to have a separate place to discuss miso isomorphic idiomatic design, and it also shows users how to setup a miso app outside of miso's examples directory.

**Comment by FPtje** [comment]
That's more of a question for @dmjio

**Comment by dmjio** [comment]
`miso`'s `README` actually links to this example in the section entitled `Isomorphic`, is this sufficient?

**Comment by FPtje** [comment]
To me personally it is.

**Comment by FPtje** [comment]
I can understand, by the way, that one would want the example to always stay up to date with Miso, but I don't think that warrants putting it in Miso's repository.
