### ISSUE TITLE
Views that change the tag structure

### ISSUE THREAD

**Issue by tkvogt** [FPtje/miso-isomorphic-example#9]
Imagine to have a view with three buttons, and another view with four buttons (I only added another "+"-button):

```haskell
-- View function of the Home route
homeView :: Model -> View Action
homeView m =
    div_ []
      [ div_
        []
        [ button_ [ onClick SubtractOne ] [ text "-" ]
        , text $ Miso.ms $ show $ _counterValue m
        , button_ [ onClick AddOne ] [ text "+" ]
        , button_ [ onClick AddOne ] [ text "+" ]
        ]
      , button_ [ onClick $ ChangeURI flippedLink ] [ text "Go to /flipped" ]
      ]

-- View function of the Home route
flippedView :: Model -> View Action
flippedView m =
    div_ []
      [ div_
        []
        [ button_ [ onClick AddOne ] [ text "+" ]
        , text $ Miso.ms $ show $ _counterValue m
        , button_ [ onClick SubtractOne ] [ text "-" ]
        ]
      , button_ [ onClick $ ChangeURI homeLink ] [ text "Go to /" ]
      ]
```
But when you try this, then you see the second "+" button in both views, although it should vanish in flippedView.

**Comment by FPtje** [comment]
I copy pasted your code into the example, but it works as expected. I see two `+` buttons in the home view, and only one in the flipped view.  I don't see the second `+` in the flipped view.

Are you building it with nix? If not, what version of miso are you running?

I'm closing the issue, but you can still reply.
